// Generated by the Ballerina OpenAPI tool from
// specs/design/components/ticket-api/openapi.yaml, then filled in by hand:
// the listener binding, the InterceptableService wiring, and every resource
// body.

import ballerina/http;
import ballerina/sql;
import ballerina/time;
import ballerina/uuid;

listener http:Listener ep0 = new (9090);

service http:InterceptableService / on ep0 {
    public function createInterceptors() returns AssertionInterceptor => new;

    // A customer submits a new support ticket — public, no auth. Classifies
    // and drafts a reply via triage-agent before responding, and persists
    // nothing at all when that call fails.
    resource function post tickets(@http:Payload NewTicket payload) returns Ticket|ErrorBadRequest|error {
        string customerEmail = payload.customerEmail.trim();
        string subject = payload.subject.trim();
        string ticketBody = payload.body.trim();
        if customerEmail == "" || subject == "" || ticketBody == "" {
            return <ErrorBadRequest>{
                body: {code: 400, message: "customerEmail, subject and body are all required"}
            };
        }

        string ticketId = uuid:createRandomUuid();
        // REQUIRED before this operation responds — an unclassified ticket
        // is never stored.
        TriageResult triage = check classifyTicket(ticketId, subject, ticketBody);

        time:Utc createdAt = time:utcNow();
        TicketRow ticketRow = {
            id: ticketId,
            customerEmail: customerEmail,
            subject: subject,
            body: ticketBody,
            urgency: triage.urgency,
            status: "triaged",
            createdAt: createdAt
        };
        check insertTicket(ticketRow);

        ReplyRow replyRow = {
            id: uuid:createRandomUuid(),
            ticketId: ticketId,
            body: triage.reply,
            status: "draft",
            approvedAt: (),
            sentAt: ()
        };
        check insertReply(replyRow);

        return ticketToApi(ticketRow);
    }

    // Every ticket in the triage queue — tickets:read-all, every row.
    resource function get tickets(http:RequestContext ctx, Urgency? urgency,
            "submitted"|"triaged"|"replied"? status, int 'limit = 20, int offset = 0)
            returns inline_response_200|ErrorUnauthorized|http:Unauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return caller;
        }

        string? urgencyFilter = urgency is Urgency ? urgency : ();
        string? statusFilter = status is string ? status : ();
        int pageLimit = 'limit > 100 ? 100 : 'limit;
        int pageOffset = offset < 0 ? 0 : offset;

        TicketRow[] rows = check listTickets(urgencyFilter, statusFilter, pageLimit, pageOffset);
        int total = check countTickets(urgencyFilter, statusFilter);
        Ticket[] data = from TicketRow row in rows
            select ticketToApi(row);

        string? next = ();
        if pageOffset + pageLimit < total {
            next = buildPageUri(urgencyFilter, statusFilter, pageLimit, pageOffset + pageLimit);
        }
        string? previous = ();
        if pageOffset > 0 {
            int prevOffset = pageOffset - pageLimit;
            previous = buildPageUri(urgencyFilter, statusFilter, pageLimit, prevOffset < 0 ? 0 : prevOffset);
        }

        inline_response_200 page = {count: total, next: next, previous: previous, data: data};
        return page;
    }

    // Every ticket's detail, including its drafted reply — tickets:read-all.
    resource function get tickets/[string ticketId](http:RequestContext ctx)
            returns TicketDetail|ErrorNotFound|http:Unauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return caller;
        }

        TicketRow|error ticketRow = findTicketById(ticketId);
        if ticketRow is sql:NoRowsError {
            return notFound();
        }
        if ticketRow is error {
            return ticketRow;
        }

        ReplyRow|error replyRow = findReplyByTicketId(ticketId);
        if replyRow is sql:NoRowsError {
            return notFound();
        }
        if replyRow is error {
            return replyRow;
        }

        Ticket ticket = ticketToApi(ticketRow);
        TicketDetail detail = {
            id: ticket.id,
            customerEmail: ticket.customerEmail,
            subject: ticket.subject,
            urgency: ticket.urgency,
            status: ticket.status,
            createdAt: ticket.createdAt,
            body: ticketRow.body,
            reply: replyToApi(replyRow)
        };
        return detail;
    }

    // Edit a ticket's drafted reply before approving it — tickets:update.
    resource function patch tickets/[string ticketId]/reply(http:RequestContext ctx, @http:Payload ReplyUpdate payload)
            returns Reply|ErrorNotFound|ErrorBadRequest|http:Unauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return caller;
        }

        string newBody = payload.body.trim();
        if newBody == "" {
            return <ErrorBadRequest>{body: {code: 400, message: "body is required"}};
        }

        int updated = check updateReplyBody(ticketId, newBody);
        if updated == 0 {
            return notFound();
        }

        ReplyRow|error replyRow = findReplyByTicketId(ticketId);
        if replyRow is error {
            return replyRow;
        }
        return replyToApi(replyRow);
    }

    // Approve a ticket's reply so it is sent to the customer by email —
    // tickets:approve. The email carries the current (possibly edited)
    // body; an unapproved reply is never sent.
    resource function post tickets/[string ticketId]/reply/approve(http:RequestContext ctx)
            returns ReplyOk|ErrorNotFound|http:Unauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return caller;
        }

        TicketRow|error ticketRow = findTicketById(ticketId);
        if ticketRow is sql:NoRowsError {
            return notFound();
        }
        if ticketRow is error {
            return ticketRow;
        }

        ReplyRow|error replyRow = findReplyByTicketId(ticketId);
        if replyRow is sql:NoRowsError {
            return notFound();
        }
        if replyRow is error {
            return replyRow;
        }

        time:Utc approvedAt = time:utcNow();
        check markReplyApproved(ticketId, approvedAt);

        check sendApprovedReplyEmail(ticketRow.customerEmail, "Re: " + ticketRow.subject, replyRow.body);

        time:Utc sentAt = time:utcNow();
        check markReplySent(ticketId, sentAt);
        check markTicketStatus(ticketId, "replied");

        ReplyRow sentReply = {
            id: replyRow.id,
            ticketId: replyRow.ticketId,
            body: replyRow.body,
            status: "sent",
            approvedAt: approvedAt,
            sentAt: sentAt
        };
        return <ReplyOk>{body: replyToApi(sentReply)};
    }
}

function notFound() returns ErrorNotFound {
    return <ErrorNotFound>{body: {code: 404, message: "no ticket with that id"}};
}

function ticketToApi(TicketRow row) returns Ticket {
    return {
        id: row.id,
        customerEmail: row.customerEmail,
        subject: row.subject,
        urgency: <Urgency>row.urgency,
        status: <"submitted"|"triaged"|"replied">row.status,
        createdAt: time:utcToString(row.createdAt)
    };
}

function replyToApi(ReplyRow row) returns Reply {
    return {
        id: row.id,
        ticketId: row.ticketId,
        body: row.body,
        status: <"draft"|"approved"|"sent">row.status,
        approvedAt: utcToOptionalString(row.approvedAt),
        sentAt: utcToOptionalString(row.sentAt)
    };
}

function buildPageUri(string? urgency, string? status, int pageLimit, int pageOffset) returns string {
    string uri = string `/tickets?limit=${pageLimit}&offset=${pageOffset}`;
    if urgency is string {
        uri = uri + "&urgency=" + urgency;
    }
    if status is string {
        uri = uri + "&status=" + status;
    }
    return uri;
}

public type Ticket record {
    string id;
    string customerEmail;
    string subject;
    Urgency urgency;
    "submitted"|"triaged"|"replied" status;
    string createdAt;
};

public type ErrorNotFound record {|
    *http:NotFound;
    Error body;
|};

public type ReplyUpdate record {
    string body;
};

public type ReplyOk record {|
    *http:Ok;
    Reply body;
|};

public type inline_response_200 record {
    # total matching tickets
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    Ticket[] data;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type Reply record {
    string id;
    string ticketId;
    string body;
    "draft"|"approved"|"sent" status;
    string? approvedAt?;
    string? sentAt?;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type Urgency "Low"|"Medium"|"High"|"Critical";

public type TicketDetail record {
    *Ticket;
    string body;
    Reply reply;
};

public type ErrorUnauthorized record {|
    *http:Unauthorized;
    Error body;
|};

public type NewTicket record {
    string customerEmail;
    string subject;
    string body;
};
